version: "3.9"
services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    # Shared Memory Optimization
    shm_size: '8589934592'
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
    expose:
      - "8888"
    # Port mapping for Jupyter Notebook / Web interface
    ports:
      - "8888:8888"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace

    # Setting for vGPU (Disabled in normal GPU Environments)
    #environment:
    #  - "NVIDIA_VISIBLE_DEVICES=all"
    #  - "NVIDIA_DRIVER_CAPABILITIES=all"
    # Hard-coded GPU IDs to ensure compatibility with local hardware setup
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
